Repository Bar-Spot-Capstone/bar-spot, pull requests merged in 2024-04, with the labels that each got.

#64 BS-41-Group-&-invite-UI
  frontend/src/components/Group.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/styles/NavBar.css
  server/src/controllers/User.ts
  server/src/controllers/UserGroup.ts
  server/src/routes/User.ts
  server/src/test/user.test.ts
  server/src/test/usergroup.test.ts
Labels: enhancement

#65 BS-42-pub-info-on-click
  frontend/src/components/QuickInfo.tsx
  frontend/src/components/TimerInput.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/MapView.tsx
  frontend/src/styles/MapView.css
  frontend/src/types/types.ts
  package-lock.json
  server/package-lock.json
Labels: enhancement

#66 BS-44-Group-system-revamp
  server/src/controllers/Invitations.ts
  server/src/controllers/UserGroup.ts
  server/src/index.ts
  server/src/models/Invitations.ts
  server/src/routes/Invitations.ts
  server/src/routes/UserGroup.ts
  server/src/test/invitation.test.ts
  server/src/test/usergroup.test.ts
Labels: enhancement

#67 BS-46-Favorite-integration
  frontend/src/pages/Profile.tsx
Labels: enhancement

#68 BS-45-Group-endpoint-integration
  frontend/src/components/Group.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/state/slices/groupSlice.ts
  frontend/src/state/slices/userSlice.ts
  frontend/src/state/store.ts
  frontend/src/types/types.ts
  server/src/controllers/UserGroup.ts
  server/src/routes/UserGroup.ts
  server/src/test/usergroup.test.ts
Labels: enhancement

#71 BS-48-Git-pages-packages-and-scripts
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement

#72 BS-48-Script-for-build
  .github/workflows/deploy.yml
  .github/workflows/server-test.yml
  frontend/package.json
  frontend/vite.config.ts
Labels: enhancement

#73 BS-Actions-patch-1
  .github/workflows/deploy.yml
Labels: bug, enhancement

#75 BS-Action-Patch-2
  .github/workflows/deploy.yml
Labels: enhancement

#74 BS-Prod-packages
  .github/workflows/deploy.yml
  .github/workflows/server-test.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/vite.config.ts
Labels: bug, enhancement

#76 BS-48-Changed-base-url
  frontend/package.json
  frontend/vite.config.ts
Labels: bug, enhancement

#77 BS-48-Changed-base
  frontend/vite.config.ts
Labels: enhancement

#80 BS-48-Reverted-path-change-and-changed-base-url
  frontend/src/main.tsx
  frontend/vite.config.ts
Labels: bug

#82 BS-48-Changed-base
  frontend/vite.config.ts
Labels: bug

#83 BS-48-Adjusted-router-paths
  frontend/src/main.tsx
Labels: bug

#84 BS-48-Reverted-and-added-slash-to-login
  frontend/src/main.tsx
Labels: bug

#87 BS-48-Fetchs-now-call-from-deployed-server
  frontend/src/components/Group.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/pages/CreateNewAcc.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/MapView.tsx
  frontend/src/pages/Profile.tsx
  frontend/src/types/fetchCall.tsx
Labels: enhancement

#89 B3-43-info-UI-and-bar-sorting
  frontend/package-lock.json
  frontend/src/components/CardInfo.tsx
  frontend/src/components/MoreInfo.tsx
  frontend/src/components/QuickInfo.tsx
  frontend/src/pages/MapView.tsx
  frontend/src/styles/MapView.css
  frontend/src/types/types.ts
  server/package-lock.json
Labels: enhancement

#90 BS-51-updated-cors-settings
  server/src/index.ts
Labels: enhancement

#91 BS-47-JWT-auth
  frontend/src/components/Group.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/pages/Login.tsx
  frontend/src/pages/Profile.tsx
  server/package-lock.json
  server/package.json
  server/src/controllers/User.ts
  server/src/index.ts
  server/src/routes/Favorites.ts
  server/src/routes/Invitations.ts
  server/src/routes/User.ts
  server/src/routes/UserGroup.ts
  server/src/routes/Visited.ts
  server/src/test/user.test.ts
Labels: enhancement

#92 BS-50-Displaying-directions
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/CardInfo.tsx
  frontend/src/components/MoreInfo.tsx
  frontend/src/components/QuickInfo.tsx
  frontend/src/main.tsx
  frontend/src/pages/Experimental.tsx
  frontend/src/pages/MapView.tsx
  server/src/index.ts
Labels: enhancement
